spring:
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/nnshop?useSSL=false&serverTimeZone=Asia/Shanghai
    username: root
    password: root

  #热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**

  #文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# mybatis配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    # 开启驼峰命名支持
    map-underscore-to-camel-case: true

#mybatis日志
logging:
  level:
    cn:
      highedu:
        boot: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html


